name: Mutation Testing

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 0'  # Every Sunday at 4am UTC

jobs:
  mutation:
    runs-on: ubuntu-latest
    env:
      UV_PYTHON: '3.13'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install project dependencies (all extras)
        run: uv sync --all-extras

      - name: Run mutation tests with mutmut
        run: |
          uv run mutmut run
          uv run mutmut results

      - name: Check mutation score threshold
        run: uv run python scripts/check_mutmut_threshold.py 90

      - name: Generate mutation badge
        run: uv run python scripts/generate_badge.py --type mutation --input mutmut_cache --output mutmut-badge.svg

      - name: Upload mutation badge artifact
        uses: actions/upload-artifact@v4
        with:
          name: mutation-badge
          path: mutmut-badge.svg
      - name: Commit and push mutation badge to main
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --ff-only
          git add mutmut-badge.svg
          git commit -m "chore: update mutation badge [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
